In [15]:
import pandas as pd
import numpy as np

list1=[11,22,33,44]
sl=pd.Series(list1)
sl


0    11
1    22
2    33
3    44
dtype: int64

In [16]:
sl1=pd.Series(['a','b','c','d'])
sl1

0    a
1    b
2    c
3    d
dtype: object

In [12]:
import pandas as pd
import numpy as np
d={
  'A':11,
  'B':22,
  'C':33,
  'D':44,
 }
sd=pd.Series(d)
sd

A    11
B    22
C    33
D    44
dtype: int64

In [13]:
import pandas as pd
import numpy as np
import random 
d={
  'A':np.random.randint(0,10,size=(2,3)),
  'B':np.random.randint(0,10,size=(2,3)), 
  'C':np.random.randint(0,10,size=(2,3)),
  'D':np.random.randint(0,10,size=(2,3)),
 }
sD=pd.Series(d)
sD

A    [[2, 0, 6], [0, 4, 6]]
B    [[7, 0, 1], [5, 8, 5]]
C    [[4, 1, 6], [1, 9, 9]]
D    [[0, 9, 3], [7, 1, 5]]
dtype: object

In [27]:
# print(sD.value())
sD.values


array([array([[2, 0, 6],
              [0, 4, 6]]), array([[7, 0, 1],
                                  [5, 8, 5]]), array([[4, 1, 6],
                                                      [1, 9, 9]]),
       array([[0, 9, 3],
              [7, 1, 5]])], dtype=object)

In [23]:
sD.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [34]:
import pandas as pd
import numpy as np
import random 
d={
  'A':np.random.randint(0,10,size=(2,3)),
  'B':np.random.randint(0,10,size=(2,3)), 
  'C':np.random.randint(0,10,size=(2,3)),
  'D':np.random.randint(0,10,size=(2,3)),
 }
sD=pd.Series(d)
sD


A    [[0, 6, 6], [0, 0, 1]]
C    [[7, 8, 7], [3, 4, 3]]
D    [[0, 8, 7], [3, 7, 8]]
dtype: object

In [42]:

sD['A']


array([[0, 6, 6],
       [0, 0, 1]])

In [46]:
print(sD[['A']])
print(sD['A'])
sD.loc['A']

A    [[0, 6, 6], [0, 0, 1]]
dtype: object
[[0 6 6]
 [0 0 1]]


array([[0, 6, 6],
       [0, 0, 1]])

A    [[0, 6, 6], [0, 0, 1]]
B    [[7, 6, 5], [7, 0, 8]]
dtype: object

In [45]:
sD.loc['A']

array([[0, 6, 6],
       [0, 0, 1]])