In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)
type(a)


[1 2 3]


numpy.ndarray

In [2]:
import numpy as np
a=np.array(( 1,2,3),dtype=float)
print(a)
type(a)

[1. 2. 3.]


numpy.ndarray

In [7]:
# int8:(-128,127)
import numpy as np
a=np.array(( 170,248,-399),dtype=np.int8)
print(a)
type(a)

[-86  -8 113]


numpy.ndarray

In [9]:
# int16 (-32768到32767)
import numpy as np
a=np.array(( 1000,2099,-30770),dtype=np.int16)
print(a)

[  1000   2099 -30770]


In [18]:
# float (16:半精度，占2个字节；32：单精度，占4个字节；64：双精度，占8个字节)
import numpy as np
a=np.array((  1.09873453,2.99743453,3.77345346),dtype=np.float16)
b=np.array((  1.09873453,2.99743453,3.77345346),dtype=np.float32)
c=np.array(( 1.0987345387,2.9974345387,3.7734534687),dtype=np.float64)
print(a,b,c)

[1.099 2.998 3.773] [1.0987345 2.9974346 3.7734535] [1.09873454 2.99743454 3.77345347]


In [24]:
import numpy as np
a=np.array([1+2j,3+4j,5+6j],dtype=np.complex64)
print(a)

[1.+2.j 3.+4.j 5.+6.j]


In [22]:
# import numpy as np
# a=np.array((True,False,True),dtype=np.bool)


import numpy as np

a = np.array([True, False, True], dtype=np.bool_)
print(a)

[ True False  True]


In [32]:
a=np.array([1,2,3],dtype=np.uint32)
a.dtype
# dtype('uint32')
b=a.astype(np.int32)
b.dtype 
# dtype('int32') 

dtype('int32')

In [34]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a=np.arange(10,30,5)
a

array([10, 15, 20, 25])

In [36]:
a=np.linspace(0,10,10)
print(a)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [41]:
c=np.linspace(0,10,10,retstep=True)
c

(array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
         5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ]),
 1.1111111111111112)

In [51]:

a=np.array([20,30,40,50])
b=np.arange(4)
b
#array([0,1,2,3])
c=a-b
c
# array([20, 29, 38, 47])
b**2
# array([0, 1, 4, 9], dtype=int32)
10*np.sin(a)
# array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [57]:
A = np.array( [[1,1],[0,1]] )          
B = np.array( [[2,0],[3,4]] )
A*B  #哈达玛积
# array([[2, 0],[0, 4]])

A @ B #矩阵相乘             
# array([[5, 4],
#        [3, 4]])
A.dot(B)     #矩阵相乘               
# array([[5, 4],[3, 4]])

array([[5, 4],
       [3, 4]])

In [58]:
import numpy as np
a=np.array([1,2,3])
print(a)
type(a)


[1 2 3]


numpy.ndarray

In [59]:
import numpy as np
a=np.array(( 1,2,3),dtype=float)
print(a)
type(a)

[1. 2. 3.]


numpy.ndarray

In [71]:
import numpy as np
# from math import pi 

a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name
# 'float64'
print(a,b)
# [1 1 1] [0.         1.57079633 3.14159265]
c=a+b
c
# array([1.        , 2.57079633, 4.14159265])
c.dtype.name
# 'float64'


[1 1 1] [0.         1.57079633 3.14159265]


In [75]:
# a=np.ones(3,dtype=np.int32)
# b=np.linspace(0,pi,3)
# c=a+b
d=np.exp(c*1j)
d
# d.dtype.name

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [84]:
import numpy as np 
np.__version__
print(np.info(np.add))
# info()函数打印帮助信息

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

创建一个从30到50的所有偶数整数的数组,取值 [30,50):[是闭区间，）是开区间
[30,50): 30<= , 50>,大于等于30，小于50

In [77]:

# 创建一个从30到50的所有偶数整数的数组,取值 [30,50):[是闭区间，）是开区间
# # [30,50): 30<= , 50>,大于等于30，小于50
import numpy as np 
array=np.arange(30,50,2)
# arange(start , stop , step) arange 函数包含start，不包含stop，
# 如果想要小于等于50，即包含50，stop这里得写成51
print(array)


[30 32 34 36 38 40 42 44 46 48]


In [86]:
# 带给定的数组中提取出奇数，并且放在另一个数组中
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]#在numpy中，变量名加[]就是遍历列表中每一个值
# array([1, 3, 5, 7, 9])


array([1, 3, 5, 7, 9])

In [ ]:
# 编写一个NumPy程序，创建介于